# Generated by Django 4.1 on 2022-08-06 16:56

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="mustn't be empty", max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.PositiveBigIntegerField(blank=True, null=True)),
                ('specialize', models.CharField(help_text="mustn't be empty", max_length=80)),
                ('description', models.TextField(help_text="mustn't be empty", max_length=250)),
                ('country', models.CharField(help_text="mustn't be empty", max_length=60)),
                ('city', models.CharField(help_text="mustn't be empty", max_length=60)),
                ('lives_in', models.CharField(help_text="mustn't be empty", max_length=120)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/owner_profile')),
                ('cv', models.FileField(blank=True, help_text='Available file types: (.pdf, .doc, .docx) \n        max file size: 1.5 mb', null=True, upload_to='owner_cv', validators=[account.validators.valid_file_type_cv, account.validators.valid_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
