# Generated by Django 4.1 on 2022-08-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Required', max_length=120)),
                ('specialize', models.CharField(help_text='Required', max_length=100)),
                ('technalogies', models.CharField(help_text='Required!!! \n        Example: Python, Django, DRF, Js, Web Socket ...', max_length=200)),
                ('from_date', models.DateField(help_text='Required')),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Experiances',
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=60)),
                ('slug', models.CharField(help_text='Required!!! \n        Slug should be shorter than title         \nExample: \n        Title: Web development \nSlug: Web', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Categories',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(help_text='Required', max_length=100)),
                ('specialize', models.CharField(help_text='Required', max_length=100)),
                ('degree', models.CharField(help_text='Required', max_length=80)),
                ('from_date', models.DateField(help_text='Required')),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Studies',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=120)),
                ('link', models.CharField(help_text='Required', max_length=250)),
                ('image', models.ImageField(upload_to='images/portfolio_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='Required', on_delete=django.db.models.deletion.CASCADE, to='my_portfolio.portfoliocategory')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
            },
        ),
    ]
